### PR TITLE
add connect-repl

### PR DESCRIPTION
**Pull request by listentolist**

### CODE REVIEW

**Comment by alexherbo2** [comment]
How connect.kak can leverage the use of a REPL?

**Comment by listentolist** [comment]
When working on a script that uses connect.kak it is useful to be able to test parts of it by sending it to a connected REPL. It would be just convenient if I can simply use the `repl-send-text` command for that. Furthermore when having a connected terminal one can edit a long command in a scratch buffer and send it to the terminal.

**Comment by alexherbo2** [comment]
But when you use the REPL, you use the connect.kak’s features?

**Comment by listentolist** [comment]
Yes. For example when writing a plugin that uses connect.kak commands I can run `connect-repl bash` in Kakoune and interactively test parts of it by sending a selection to the connected REPL.

**Comment by alexherbo2** [comment]
I hesitate to merge it.  We have the `>` (`connect-terminal`) and `$` (`connect-shell`) commands.  I would like to unify the implementations and make a connected terminal or program a REPL at any time.

**Comment by alexherbo2** [comment]
@listentolist Can you test the latest commit 5ad59e5201d21ac1221be7c373bd25623efe8337 and implementation?

**Comment by listentolist** [comment]
Thank you! `connect repl-new` works as expected.

**Comment by alexherbo2** [comment]
Very happy with that.

We can now use the explicit:

``` kak
connect tmux-terminal-horizontal
```

and all other flavors.

**Comment by useredsa** [comment]
> Yes. For example when writing a plugin that uses connect.kak commands I can run `connect-repl bash` in Kakoune and interactively test parts of it by sending a selection to the connected REPL.

I was also using it a lot. As a repl for bash scripts for example. `:fifo` is just great. Also as a connected repl for compilation: ``$(:get %opt{makecmd}) `:it` ``

**Comment by alexherbo2** [comment]
I’ve added the `@` (think [kitty]’s REPL) command, alongside the `+` popup command.

[kitty]: https://sw.kovidgoyal.net/kitty/

**Example** – Open a connected [Janet] REPL:

``` kak
@ janet
```

[Janet]: https://janet-lang.org

**Example** – Open files with [fzf] in a popup window:

``` kak
+ :fzf
```

[fzf]: https://github.com/junegunn/fzf

**Comment by useredsa** [comment]
> I’ve added the `@` (think [kitty](https://sw.kovidgoyal.net/kitty/)’s REPL) command, alongside the `+` popup command.
> 
> **Example** – Open a connected [Janet](https://janet-lang.org) REPL:
> 
> ```
> @ janet
> ```
> 
> **Example** – Open files with [fzf](https://github.com/junegunn/fzf) in a popup window:
> 
> ```
> + :fzf
> ```

Default popup handling is very nice. I had this in my `kakrc`:

```
    define-command fzf-files -override -params .. -file-completion -docstring 'Open files with fzf' %{
        terminal-set global kitty kitty-terminal-tab kitty-focus
        > :fzf-files %arg{@}
        terminal-set global x11 x11-terminal x11-focus
    }
    define-command fzf-buffers -override -params ..1 -buffer-completion -docstring 'Open buffers with fzf' %{
        terminal-set global kitty kitty-terminal-tab kitty-focus
        > :fzf-buffers %arg{@}
        terminal-set global x11 x11-terminal x11-focus
    }
```

Connected repls are also useful.

**Pull request closed without merging**
